/** All the names and types for the cards */
var pictures = [
    {
        "type": 2,
        "img": "2C"
    }, {
        "type": 2,
        "img": "2D"
    }, {
        "type": 2,
        "img": "2H"
    }, {
        "type": 2,
        "img": "2S"
    }, {
        "type": 3,
        "img": "3C"
    }, {
        "type": 3,
        "img": "3D"
    }, {
        "type": 3,
        "img": "3H"
    }, {
        "type": 3,
        "img": "3S"
    }, {
        "type": 4,
        "img": "4C"
    }, {
        "type": 4,
        "img": "4D"
    }, {
        "type": 4,
        "img": "4H"
    }, {
        "type": 4,
        "img": "4S"
    }, {
        "type": 5,
        "img": "5C"
    }, {
        "type": 5,
        "img": "5D"
    }, {
        "type": 5,
        "img": "5H"
    }, {
        "type": 5,
        "img": "5S"
    }, {
        "type": 6,
        "img": "6C"
    }, {
        "type": 6,
        "img": "6D"
    }, {
        "type": 6,
        "img": "6H"
    }, {
        "type": 6,
        "img": "6S"
    }, {
        "type": 7,
        "img": "7C"
    }, {
        "type": 7,
        "img": "7D"
    }, {
        "type": 7,
        "img": "7H"
    }, {
        "type": 7,
        "img": "7S"
    }, {
        "type": 8,
        "img": "8C"
    }, {
        "type": 8,
        "img": "8D"
    }, {
        "type": 8,
        "img": "8H"
    }, {
        "type": 8,
        "img": "8S"
    }, {
        "type": 9,
        "img": "9C"
    }, {
        "type": 9,
        "img": "9D"
    }, {
        "type": 9,
        "img": "9H"
    }, {
        "type": 9,
        "img": "9S"
    }, {
        "type": 10,
        "img": "10C"
    }, {
        "type": 10,
        "img": "10D"
    }, {
        "type": 10,
        "img": "10H"
    }, {
        "type": 10,
        "img": "10S"
    }, {
        "type": "A",
        "img": "AC"
    }, {
        "type": "A",
        "img": "AD"
    }, {
        "type": "A",
        "img": "AH"
    }, {
        "type": "A",
        "img": "AS"
    }, {
        "type": "J",
        "img": "JC"
    }, {
        "type": "J",
        "img": "JD"
    }, {
        "type": "J",
        "img": "JH"
    }, {
        "type": "J",
        "img": "JS"
    }, {
        "type": "K",
        "img": "KC"
    }, {
        "type": "K",
        "img": "KD"
    }, {
        "type": "K",
        "img": "KH"
    }, {
        "type": "K",
        "img": "KS"
    }, {
        "type": "Q",
        "img": "QC"
    }, {
        "type": "Q",
        "img": "QD"
    }, {
        "type": "Q",
        "img": "QH"
    }, {
        "type": "Q",
        "img": "QS"
    }
];